[workspace]
resolver = "2"
members = ["crates/mmio-core", "crates/mmio-emu", "crates/mmio-infer", "crates/mmio-fuzz"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
authors = ["t-anas <alhachemi.anas@proton.me>"]
license = "MIT"
repository = "https://github.com/t-anas/mmio-fuzz"
readme = "README.md"

[workspace.dependencies]
mmio-core = { path = "crates/mmio-core", version = "0.1.0" }
mmio-emu = { path = "crates/mmio-emu", version = "0.1.0" }
mmio-infer = { path = "crates/mmio-infer", version = "0.1.0" }
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
object = { version = "0.36", default-features = false, features = ["read", "elf"] }
blake3 = "1"
rand = "0.8"
rand_chacha = "0.3"

[profile.release]
lto = "thin"
codegen-units = 1

[profile.fuzz]
inherits = "release"
debug = true
